// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/telemetry.proto

package telemetry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerTelemetry_Stream_FullMethodName   = "/telemetry.WorkerTelemetry/Stream"
	WorkerTelemetry_Generate_FullMethodName = "/telemetry.WorkerTelemetry/Generate"
)

// WorkerTelemetryClient is the client API for WorkerTelemetry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerTelemetryClient interface {
	// Worker pushes telemetry to gateway continuously.
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatAck], error)
	// Gateway asks worker to run a generation, streamed back token by token.
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Token], error)
}

type workerTelemetryClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerTelemetryClient(cc grpc.ClientConnInterface) WorkerTelemetryClient {
	return &workerTelemetryClient{cc}
}

func (c *workerTelemetryClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerTelemetry_ServiceDesc.Streams[0], WorkerTelemetry_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatRequest, HeartbeatAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerTelemetry_StreamClient = grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatAck]

func (c *workerTelemetryClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Token], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerTelemetry_ServiceDesc.Streams[1], WorkerTelemetry_Generate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateRequest, Token]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerTelemetry_GenerateClient = grpc.ServerStreamingClient[Token]

// WorkerTelemetryServer is the server API for WorkerTelemetry service.
// All implementations must embed UnimplementedWorkerTelemetryServer
// for forward compatibility.
type WorkerTelemetryServer interface {
	// Worker pushes telemetry to gateway continuously.
	Stream(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatAck]) error
	// Gateway asks worker to run a generation, streamed back token by token.
	Generate(*GenerateRequest, grpc.ServerStreamingServer[Token]) error
	mustEmbedUnimplementedWorkerTelemetryServer()
}

// UnimplementedWorkerTelemetryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerTelemetryServer struct{}

func (UnimplementedWorkerTelemetryServer) Stream(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatAck]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedWorkerTelemetryServer) Generate(*GenerateRequest, grpc.ServerStreamingServer[Token]) error {
	return status.Error(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedWorkerTelemetryServer) mustEmbedUnimplementedWorkerTelemetryServer() {}
func (UnimplementedWorkerTelemetryServer) testEmbeddedByValue()                         {}

// UnsafeWorkerTelemetryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerTelemetryServer will
// result in compilation errors.
type UnsafeWorkerTelemetryServer interface {
	mustEmbedUnimplementedWorkerTelemetryServer()
}

func RegisterWorkerTelemetryServer(s grpc.ServiceRegistrar, srv WorkerTelemetryServer) {
	// If the following call panics, it indicates UnimplementedWorkerTelemetryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerTelemetry_ServiceDesc, srv)
}

func _WorkerTelemetry_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerTelemetryServer).Stream(&grpc.GenericServerStream[HeartbeatRequest, HeartbeatAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerTelemetry_StreamServer = grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatAck]

func _WorkerTelemetry_Generate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerTelemetryServer).Generate(m, &grpc.GenericServerStream[GenerateRequest, Token]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerTelemetry_GenerateServer = grpc.ServerStreamingServer[Token]

// WorkerTelemetry_ServiceDesc is the grpc.ServiceDesc for WorkerTelemetry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerTelemetry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.WorkerTelemetry",
	HandlerType: (*WorkerTelemetryServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _WorkerTelemetry_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Generate",
			Handler:       _WorkerTelemetry_Generate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/telemetry.proto",
}
